common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>

development:
  <<: *common
  database: liftit_dev

test:
  <<: *common
  database: liftit_test

production:
  <<: *common
  database: liftit_production
  pool: 16
